# {workspaceDir}/docker/docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:alpine
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: lumos
      POSTGRES_PASSWORD: password
    volumes:
      - ../cache/activity/postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ../docker/web3/web3-indexer-sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  ckb:
    build:
      context: layer1
      args: 
        DOCKER_PREBUILD_IMAGE: "${DOCKER_PREBUILD_IMAGE_NAME}:${DOCKER_PREBUILD_IMAGE_TAG}"
    ports:
    - 28114:28114 # rpc.ws_listen_address
    - 8114:8114
    - 8115:8115   # 8115 is not using for now, but we may need it when extend kicker in the future
    volumes:
    - ../ckb:/ckb 
    - ../cache/activity/ckb-chain-data:/usr/local/ckb-chain-data
    environment:
      # env of layer 1:
      CKB_CHAIN: dev
      BA_ARG: 0x43d509d97f26007a285f39241cffcd411157196c
      BA_CODE_HASH: 0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8
      BA_HASH_TYPE: type
      BA_MESSAGE: 0x1234

  godwoken:
    build: 
      context: layer2
      args: 
        DOCKER_PREBUILD_IMAGE: "${DOCKER_PREBUILD_IMAGE_NAME}:${DOCKER_PREBUILD_IMAGE_TAG}"
        DOCKER_MANUAL_BUILD_IMAGE: "${DOCKER_MANUAL_BUILD_IMAGE_NAME}:${DOCKER_MANUAL_BUILD_IMAGE_TAG}"
    volumes:
    - ../:/code
    - ../cache/build/usr-local-cargo:/usr/local/cargo
    - ../cache/activity/ckb-cli-data:/root/.ckb-cli
    environment:
      FORCE_GODWOKEN_REDEPLOY: ${FORCE_GODWOKEN_REDEPLOY}
      MANUAL_BUILD_GODWOKEN: ${MANUAL_BUILD_GODWOKEN}
    env_file: ./.build.mode.env
    command: bash /code/godwoken_entrypoint.sh
    ports:
      - 8116:8116
      - 8119:8119
    depends_on:
      - ckb
      - postgres
      
  polyjuice:
    build:
      context: polyjuice 
      args: 
        DOCKER_PREBUILD_IMAGE: "${DOCKER_JS_PREBUILD_IMAGE_NAME}:${DOCKER_JS_PREBUILD_IMAGE_TAG}"
    volumes:
      - ../:/code
    environment: 
      MANUAL_BUILD_POLYMAN: ${MANUAL_BUILD_POLYMAN}
    command: bash /code/docker/polyjuice/entrypoint.sh 
    ports:
      - 6101:6101
      - 6100:6100
    depends_on:
      - ckb
      - postgres
    
  call-polyman:
    build:
      context: call-polyman
      args: 
        DOCKER_PREBUILD_IMAGE: "${DOCKER_JS_PREBUILD_IMAGE_NAME}:${DOCKER_JS_PREBUILD_IMAGE_TAG}"
    volumes:
      - ../:/code
    environment: 
      MANUAL_BUILD_POLYMAN: ${MANUAL_BUILD_POLYMAN}
    command: bash /code/docker/call-polyman/entrypoint.sh 
    ports:
      - 6102:6102
    depends_on:
      - ckb
      - postgres 

  web3:
    build:
      context: web3
      args: 
        DOCKER_PREBUILD_IMAGE: "${DOCKER_JS_PREBUILD_IMAGE_NAME}:${DOCKER_JS_PREBUILD_IMAGE_TAG}"
    volumes: 
    - ../:/code # the manual-build resource all stays in /code dir
    - ../cache/activity/web3-data/address-mapping:/usr/local/godwoken-web3/address-mapping
    environment: 
      MANUAL_BUILD_WEB3: ${MANUAL_BUILD_WEB3}
      PORT: 8024
    command: bash /code/web3_entrypoint.sh
    ports:
      - 8024:8024
    depends_on: 
      - postgres
      - godwoken
  
  # gen-godwoken-schema:
  #   image: retricsu/gowoken-build_dev:ubuntu20
  #   profiles: ["cli-only"]
  #   volumes: 
  #     - ../:/code
  #   command: bash /code/docker/gen-godwoken-schema/entrypoint.sh
 
